### ISSUE TITLE
/api/stats causes an error

### ISSUE THREAD

**Issue by Puyodead1** [ZiplineProject/zipline#19]
```
(node:20707) UnhandledPromiseRejectionWarning: TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at APIController.getStats (/root/zipline/out/src/controllers/APIController.js:266:83)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

seems to come from [this line](https://github.com/ZiplineProject/zipline/blob/master/src/controllers/APIController.ts#L194)

**Comment by dicedtomatoreal** [comment]
Fixed, a commit should be coming out soon

**Comment by dicedtomatoreal** [comment]
https://github.com/ZiplineProject/zipline/commit/e9fe41e7d2f8d2e9ccb2c23a306f7004f286b2ac#diff-1c92b002d3b1a607ae6551614872a3bf  this commit should fix it. make sure to update
