### ISSUE TITLE
missing config property update

### ISSUE THREAD

**Issue by Puyodead1** [ZiplineProject/zipline#20]
```8/11/2020 6:52:03 PM err     Zipline.Config: Missing needed property on configuration: upload.route```

**Comment by dicedtomatoreal** [comment]
Fixed, a commit should be coming out soon

**Comment by dicedtomatoreal** [comment]
https://github.com/ZiplineProject/zipline/commit/e9fe41e7d2f8d2e9ccb2c23a306f7004f286b2ac#diff-f41e9d04a45c83f3b6f6e630f10117fe this should fix it :D
