### ISSUE TITLE
PostgreSQL reserves 'user' table

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#31]
**Describe the bug**
PostgreSQL reserves `user` table for system so many products use `users` table (in the plural).
In fact, users can't get `user` table contents by using psql.
Could you consider to change `user` to `users`?

**Comment by wzhouwzhou** [comment]
We should add something to support this
> If you want to use an alternative table name for the User entity you can specify it in `@Entity`: `@Entity("my_users")`. If you want to set a base prefix for all database tables in your application you can specify entityPrefix in connection options.
https://github.com/typeorm/typeorm/blob/master/docs/entities.md#what-is-entity

**Comment by mzch** [comment]
I agree that entityPrefix a user specifies will be added in config.json. How about?

**Comment by dicedtomatoreal** [comment]
Sounds like a good idea, a default value can be, ex. `zipline_users` / `zipline_images`

**Comment by mzch** [comment]
Very good! :)

**Comment by dicedtomatoreal** [comment]
I also do not think a configurable table name is a good idea, as that would become a whole mess!

**Comment by mzch** [comment]
Well, frankly speaking I also think table name isn't configurable. In short I'd like to recommend to avoid system reserved name.

**Comment by dicedtomatoreal** [comment]
Yes, I agree too, hopefully once im free i can implement bunch of cool stuff  :D

**Comment by mzch** [comment]
I have a high expectation of your works. I like Zipline very much! Thanks!
