### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by Zorotic** [ZiplineProject/zipline#37]
For the love of all things holy. please use a linter or something cause the code for this is pretty badly formatted. 

Shit we'll even supply you with a prettier/eslint config

**Comment by dicedtomatoreal** [comment]
Development on this current version has stopped recently to work on a new, exciting, rework of Zipline, which should be coming out soon in beta stages. I will run this through a linter and commit those changes soon.

**Comment by Zorotic** [comment]
> Development on this current version has stopped recently to work on a new, exciting, rework of Zipline, which should be coming out soon in beta stages. I will run this through a linter and commit those changes soon.

Ah, very good. Do you have a discord for this project?

**Comment by dicedtomatoreal** [comment]
Yes https://discord.gg/PWU8rxy
