### ISSUE TITLE
How to shorten URL or upload images?

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#43]
I have 2 questions about `next` branch.

1. How can I shorten a new url or upload an image on the Web UI?
1. When accessing `/images` from my browser, only loading circle is spinning and no image is shown. Why?

**Comment by dicedtomatoreal** [comment]
1. right as of now there is no way to shorten URLs on the web ui (i can work on this soon)
2. not sure whats happening here, can you show the browser console, and network tab & maybe try running zipline in verbose mode? (https://zipline.diced.wtf/docs/#starting-in-verbose-mode)

**Comment by mzch** [comment]
1. OK. I'm looking forward to it!.
1. Yes, I tried verbose mode but no log and no error... Database has no image record with table changing by update `next` branch, in that case I think no image message should be shown...?

- log
```
10月 25 02:16:22 ls start.sh[6334]: Issues  : https://github.com/ZiplineProject/zipline/issues
10月 25 02:16:22 ls start.sh[6334]: Docs    : https://zipline.diced.wtf/
10月 25 02:16:22 ls start.sh[6334]: Mode    : production
10月 25 02:16:22 ls start.sh[6334]: Verbose : yes
10月 25 02:16:22 ls start.sh[6334]: [10/25/2020 2:16:22 AM] verbose: searching for config...
10月 25 02:16:22 ls start.sh[6334]: [10/25/2020 2:16:22 AM] info: Preparing app...
10月 25 02:16:22 ls start.sh[6334]: [10/25/2020 2:16:22 AM] verbose: Prepared app
10月 25 02:16:23 ls start.sh[6334]: [10/25/2020 2:16:23 AM] info: server listening on 127.0.0.1:8000
10月 25 02:38:29 ls start.sh[6334]: [10/25/2020 2:38:29 AM] verbose: set cookie for mzch (1)
10月 25 02:38:29 ls start.sh[6334]: [10/25/2020 2:38:29 AM] info: mzch (1) logged in
```

- Screen Shot
<img width="1490" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/97113787-ebafc980-172f-11eb-941b-558ec32da116.png">

**Comment by dicedtomatoreal** [comment]
1. this has been added now! update to the latest version by pulling
2. once you upload an image you will not get a loading screen. You can upload images by making a request to "server.com/api/upload" with a multipart form body name file which contains the file.
