### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#45]
**Describe the bug**
After updating to 2c6ca79efac51e076dd5b4cff868c63493fed99c, 404 error occurred.

**To Reproduce**
1. `npm install`
2. `npm run build`
3. `npm start`
4. access top page via browser

**Expected behavior**
Show home page or login page.

**Screenshots**
<img width="1490" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/97261073-6af0ea80-1861-11eb-90ef-32915134f7d5.png">

**Desktop (please complete the following information if desktop):**
 - OS: macOS 10.15.7
 - Browser: Chrome 86.0.4240.111
 - Zipline Version: `next` branch, 2c6ca79efac51e076dd5b4cff868c63493fed99c

**Browser Logs (for desktop browsers)**
See screenshot.

**Comment by dicedtomatoreal** [comment]
Hm, I'm not able to reproduce this. In the latest commit I've changed the path structures yet added a redirect from / to the new /dash.. which works fine for me.

**Comment by mzch** [comment]
Mm, at `/dash`I can see normal page. For some strange reason redirection doesn't work well.

**Comment by mzch** [comment]
I re-installed Zipline and use API as below:
```
curl -X POST -H "Content-Type: application/json" -d '{"username":"mzch", "password":"password","administrator":"true"}' https://uixns.com/api/user/create
```
Then I got a response.
```
{"username":"mzch","administrator":true,"token":"token","id":1
```
Next I login via API
```
curl -X POST -H "Content-Type: application/json" -d '{"username":"mzch", "password":"password"}' https://uixns.com/api/user/login
```
Got the following response.
```
{"username":"mzch","administrator":true,"token":"token","id":1}
```
Yes, I can login successfully, but via browser:

<img width="1490" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/97271370-d0e66d80-1873-11eb-8720-0e7104f36320.png">

I can't login. Something is wrong.

**Comment by mzch** [comment]
Well, when `npm run dev`, redirection works.

**Comment by mzch** [comment]
Finally when I cleared all caches from Chrome, redirection works and I can login successfully, Thanks.

**Comment by tbnritzdoge** [comment]
#BlameGoogle

**Comment by dicedtomatoreal** [comment]
We have a setup feature once u go to the login page that will create a new user so be sure to try that out
